### ISSUE TITLE
onComplete should still pass File

### ISSUE THREAD

**Issue by adevezin** [Storj/android-libstorj#14]
Love all the new changes. One thing i noticed was that the onComplete for the DownloadFileCallback was change to String fileId, String localPath. This one alone should remain File file, String localPath, for working with the file after download.

**Comment by kaloyan-raev** [comment]
Yes, this change was necessary because the File object was transferred locally from the calling method to the callback. It's not something returned by the Bridge server. As now the calling method takes either a file id or a File object, only the file id can be transferred to the callback as a complete File object may not be available.

BTW, The idea of transferring the file id/object between the calling method and the callback was to help the client to easily map the callback to the respective file operation, e.g. make sure you update the correct notification in Android. So, the file id should be sufficient.

Is there any real use case you have broken by this change?

**Comment by dri94** [comment]
When you put it like that no lol. I agree with you. Im going to close this
