### ISSUE TITLE
Failed decrypting keys

### ISSUE THREAD

**Issue by Sketchypop** [Storj/android-libstorj#20]
Hi, I am trying to upload files to storj using Android. I am always failing to import keys. I give username password and encryption key generated by filezilla. but all the time it says failed decrypting. I have tried to generate key inside and app and import it but same result. I am stuck. I need to integrate file uploading code in my own app. Please help

**Comment by kaloyan-raev** [comment]
I assume you use the [Hello Storj](https://github.com/kaloyan-raev/hello-storj) app.

What does exactly happen when you try to import your keys? Do you see a message/toast `Keys imported`? If not, what is the error message displayed.

**Comment by Sketchypop** [comment]
![sjerr](https://user-images.githubusercontent.com/14263553/36590011-12bc4a1c-18af-11e8-9d04-54dccd00ae8c.jpg)

**Comment by Sketchypop** [comment]
This is the message

**Comment by kaloyan-raev** [comment]
This message means that the provided encryption key / mnemonic is not the one you've used for uploading files to this account so far.

The app makes an attempt to verify the provided encryption key by listing the buckets in the account and trying to decrypt the metadata of at least one bucket.

You should provide the encryption key you used with this account so far, instead of generating a new encryption key for this app.

**Comment by Sketchypop** [comment]
Is this the same encryption key which I generated in filezilla ?  Encryption key works  in Filezilla and I am able to upload files

**Comment by kaloyan-raev** [comment]
You should use the encryption key that is already registered in Filezilla. If you click the `Generate` button in Filezilla, it will generate a completely new encryption key.

You should have taken a note for the encryption key when you have setup the Storj account in Filezilla.

**Comment by kaloyan-raev** [comment]
Closing, assuming the reported issue was resolved. If not, please reopen and provide more details.
