### ISSUE TITLE
Issue while uploading files to Storj Network

### ISSUE THREAD

**Issue by crawter** [Storj/android-libstorj#22]
We faced an issue while file uploading.

It seems that while file is uploading and encrypting the whole file is placed to the virtual memory.
But RAM of the mobile devices is finite, and when file is too large - app will be crashed.

Steps to reproduce:

1. Create android emulator with next props:
API - 26
Target - Android **8.0**
RAM - 512
VM Heap - 256
Internal storage - **2048**

2. Try to upload 537mb file

Expecting result 
- file will be uploaded successfully

Actual result
- exception in unmanaged c code occurs and hosted process is killed as a result

_______________________________________________________________________________________________

Steps to reproduce:

1. Create android emulator with next props:
API - 26
Target - Android **7.1.1**
RAM - 512
VM Heap - 256
Internal storage - **512**

2. Try to upload 244mb file

Expecting result 
- file will be uploaded successfully

Actual result
- file encryption error occurs

**Comment by ValeriiLavrusko** [comment]
Steps to reproduce:

  1.Create android emulator with next props:
    API - 26
    Target - Android 8.0
    RAM - **525** mb
    VM Heap - 256
    Internal storage - **998** mb

  2.Try to upload **525** mb file

Additional info: when we try to upload the file, free space on phone storage **262** mb.

Expecting result:

- file will be uploaded successfully.

Actual result:

- exception in unmanaged c code occurs and hosted process is killed as a result.

**Comment by ValeriiLavrusko** [comment]
Steps to reproduce:

1.Create android emulator with next props:
API - 26
Target - Android 8.0
RAM - **1050** mb
VM Heap - 256
Internal storage - **998** mb

2.Try to upload **525** mb file

Additional info: when we try to upload the file, free space on phone storage **262** mb.

Expecting result:

- file will be uploaded successfully.

Actual result:

- exception in unmanaged c code occurs and hosted process is killed as a result.

**Comment by ValeriiLavrusko** [comment]
Steps to reproduce:

1.Create android emulator with next props:
API - 26
Target - Android 8.0
RAM - **1050** mb
VM Heap - 256
Internal storage - **1300** mb

2.Try to upload **525** mb file

Additional info: when we try to upload the file, free space on phone storage **576** mb.

Expecting result:

- file will be uploaded successfully.

Actual result:

- exception in unmanaged c code occurs and hosted process is killed as a result.

**Comment by RichardLitt** [comment]
:wave: Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming soon - follow along on [the blog](https://storj.io/blog) and in [our RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
