### ISSUE TITLE
Issue while downloading files to Storj Network

### ISSUE THREAD

**Issue by ValeriiLavrusko** [Storj/android-libstorj#23]
We faced an issue while file downloading. 

When trying to download a file from Storj using an emulator (or device) that has little free space (free space is less than the size of the downloaded file). The download continues until the free space is available. Then the download rolls back and starts downloading a certain amount of data. This process continues indefinitely.

Steps to reproduce:

1. Create android emulator with next props:
    API - 26
    Target - Android 8.0
    RAM - 525 mb 
    VM Heap - 256
    Internal storage - 998 mb

2. Try to download 537mb file

Expecting result:

- file will be downloaded successfully.

Actual result:

- download does not stop.

**Comment by adevezin** [comment]
Check for available  space and file size before downloading the file.

**Comment by RichardLitt** [comment]
:wave: Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming soon - follow along on [the blog](https://storj.io/blog) and in [our RocketChat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
